spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/study/jpa-roadmap/bigringdb
      username: bigring
      password: 1234
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: H2
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true